---
- name: Start NetAlertX
  block:
    - name: Create NetAlertX Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ netalertx_data_directory }}"
        - "{{ netalertx_data_directory }}/db"

    - name: Create NetAlertX Docker Container
      community.docker.docker_container:
        name: "{{ netalertx_container_name }}"
        image: "{{ netalertx_image_name }}:{{ netalertx_image_version }}"
        pull: true
        network_mode: host
        cap_drop:
          - ALL
        capabilities:
          - CHOWN
          - SETGID
          - SETUID
          - NET_ADMIN
          - NET_BIND_SERVICE
          - NET_RAW
        volumes:
          - "{{ netalertx_data_directory }}:/data"
          - /etc/localtime:/etc/localtime:ro
        tmpfs:
          - "/tmp:uid={{ netalertx_uid }},gid={{ netalertx_gid }},mode=1700,noexec,nosuid,nodev"
        env:
          TIMEZONE: "{{ ansible_nas_timezone }}"
          NETALERTX_UID: "{{ netalertx_uid }}"
          NETALERTX_GID: "{{ netalertx_gid }}"
        restart_policy: unless-stopped
        memory: "{{ netalertx_memory }}"
        labels:
          traefik.enable: "{{ netalertx_available_externally | string }}"
          traefik.http.routers.netalertx.rule: "Host(`{{ netalertx_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.netalertx.tls.certresolver: "letsencrypt"
          traefik.http.routers.netalertx.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.netalertx.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.netalertx.loadbalancer.server.port: "20211"
          homepage.group: Monitoring
          homepage.name: NetAlertX
          homepage.icon: netalertx.png
          homepage.href: "https://{{ netalertx_hostname }}.{{ ansible_nas_domain }}"
          homepage.description: Network device monitoring and alerting
  when: netalertx_enabled is true

- name: Stop NetAlertX
  block:
    - name: Stop NetAlertX
      community.docker.docker_container:
        name: "{{ netalertx_container_name }}"
        state: absent
  when: netalertx_enabled is false
