---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get TinyAuth container state
      community.docker.docker_container_info:
        name: "{{ tinyauth_container_name }}"
      register: tinyauth_result

    - name: Check TinyAuth is running
      ansible.builtin.assert:
        that:
          - tinyauth_result.container['State']['Status'] == "running"
          - tinyauth_result.container['State']['Restarting'] == false
