---
scrutiny_collector_enabled: false

# network
scrutiny_collector_hostname: "scrutiny-collector"
scrutiny_collector_api_endpoint: "{{ scrutiny_container_name }}"
scrutiny_collector_api_port: 8080

# specs
scrutiny_collector_memory: 1g

# docker
scrutiny_collector_container_name: "scrutiny_collector"
scrutiny_collector_image_name: "ghcr.io/analogj/scrutiny"
scrutiny_collector_image_version: "master-collector"
