---
ollama_enabled: false
ollama_available_externally: false

# directories
ollama_data_directory: "{{ docker_home }}/ollama"

# network
ollama_network_name: "ollama"
ollama_hostname: "ollama"
ollama_webui_hostname: "ollama_webui"
ollama_webui_port: 3881

# specs
ollama_memory: 1g
ollama_webui_memory: 1g

# docker
ollama_container_name: "ollama"
ollama_webui_container_name: "ollama_webui"

ollama_image_name: "ollama/ollama"
ollama_image_version: "latest"

ollama_webui_image_name: "ghcr.io/open-webui/open-webui"
ollama_webui_image_version: "main"
