---
pocketid_enabled: false
pocketid_available_externally: false

# directories
pocketid_data_directory: "{{ docker_home }}/pocketid"

# network
pocketid_port: "8174"
pocketid_hostname: "pocketid"

# specs
pocketid_memory: 1g

# docker
pocketid_container_name: pocketid
pocketid_image_name: "ghcr.io/pocket-id/pocket-id"
pocketid_image_version: v1
pocketid_user_id: "1000"
pocketid_group_id: "1000"

# pocketid
pocketid_app_url: https://{{ pocketid_hostname }}.{{ ansible_nas_domain }}
pocketid_encryption_key: ""
pocketid_trust_proxy: "false"
pocketid_maxmind_license_key: ""
pocketid_puid: "{{ pocketid_user_id }}"
pocketid_guid: "{{ pocketid_group_id }}"
