---
netalertx_enabled: false
netalertx_available_externally: false

# directories
netalertx_data_directory: "{{ docker_home }}/netalertx"

# network
netalertx_hostname: "netalertx"

# docker
netalertx_container_name: "netalertx"
netalertx_image_name: "ghcr.io/jokob-sk/netalertx"
netalertx_image_version: "latest"

# specs
netalertx_memory: 1g
netalertx_uid: "1001"
netalertx_gid: "1001"
