---
excalidraw_enabled: false
excalidraw_available_externally: false

# network
excalidraw_port: "3008"
excalidraw_hostname: "excalidraw"

# specs
excalidraw_memory: 1g

# docker
excalidraw_container_name: excalidraw
excalidraw_image_name: "excalidraw/excalidraw"
excalidraw_image_version: latest
