---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get pocket_id container state
      community.docker.docker_container:
        name: "{{ pocket_id_container_name }}"
      register: result

    - name: Get pocket_id postgres container state
      community.docker.docker_container:
        name: "{{ pocket_id_postgres_container_name }}"
      register: result_postgres

    - name: Check if pocketid containers are running
      ansible.builtin.assert:
        that:
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
          - result_postgres.container['State']['Status'] == "running"
          - result_postgres.container['State']['Restarting'] == false
