---
readeck_enabled: false
readeck_available_externally: false

# directories
readeck_data_directory: "{{ docker_home }}/readeck"

# config
# readeck_log_level:
# readeck_secret_key:
# readeck_allowed_hosts:
# readeck_database_source:
# readeck_email_host:
# readeck_email_port:
# readeck_email_username:
# readeck_email_password:
# readeck_email_insecure:
# readeck_email_encryption:
# readeck_email_from:
# readeck_email_noreply:
# readeck_public_share_ttl:

# network
readeck_port: "8005"
readeck_hostname: "readeck"

# specs
readeck_memory: 1g

# docker
readeck_container_name: readeck
readeck_image_name: "codeberg.org/readeck/readeck"
readeck_image_version: latest
readeck_user_id: "1000"
readeck_group_id: "1000"
