---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml
    - name: Get superproductivity app container state
      community.docker.docker_container:
        name: '{{ superproductivity_app_container_name }}'
      register: app_result
    - name: Get superproductivity webdav container state
      community.docker.docker_container:
        name: '{{ superproductivity_webdav_container_name }}'
      register: webdav_result
    - name: Check if superproductivity app container is running
      ansible.builtin.assert:
        that:
          - app_result.container['State']['Status'] == "running"
          - app_result.container['State']['Restarting'] == false
    - name: Check if superproductivity webdav container is running
      ansible.builtin.assert:
        that:
          - webdav_result.container['State']['Status'] == "running"
          - webdav_result.container['State']['Restarting'] == false
